# -*- coding: utf-8 -*-
"""villadelrey_b11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zN3ixp8mqJC2MIAOVZ5uzqvV5j_UVTHi
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam/Exam_Table.csv', skip_blank_lines=True).dropna()

df.drop_duplicates(subset=['Date', 'Site', 'Scientific Name']).to_csv('/content/drive/MyDrive/Colab Notebooks/Exam/b11_output1.csv')