# -*- coding: utf-8 -*-
"""villadelrey_b9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yB3aShfXTrh9RTFXgoT1rGpZoAhqgM-o
"""

import pandas as pd

#Display the average count per replicate interval.

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam/Exam_Table.csv', skip_blank_lines=True).dropna()

#NewTable = pd.DataFrame({'Replicate': df.Replicate, 'Interval': df.Interval, 'Count': df.Count})
#NewTable

arrays = [[df.Replicate.astype(int)]
          [df.Interval.astype]]
index = pd.MultiIndex.from_arrays(arrays, names=('Replicate', 'Interval'))
NewTable = pd.DataFrame({'Count': df.Count.astype(int)}, index=index)
NewTable


#.to_csv('/content/drive/MyDrive/Colab Notebooks/Exam/b9_output1.csv')