# -*- coding: utf-8 -*-
"""villadelrey_b10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJkDg7-AAXHO8m7ITFwjdbZjG2hSE2Xl
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam/Exam_Table.csv', skip_blank_lines=True)

values = {"Count": 0, "Size Est (cm)": 0}

df.fillna(value=values).to_csv('/content/drive/MyDrive/Colab Notebooks/Exam/b10_output1.csv')