# -*- coding: utf-8 -*-
"""villadelrey_b7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nEGonF0p653JjR43scrrNcYuFfW33xvc
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam/Exam_Table.csv', skip_blank_lines=True).dropna()

pd.DataFrame(df.Observer.unique()).to_csv('/content/drive/MyDrive/Colab Notebooks/Exam/b7_output1.csv')