# -*- coding: utf-8 -*-
"""villadelrey_b4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Tgbqx--rRDQ_r79jdUWgdfkWjhhNJYp
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam/Exam_Table.csv', skip_blank_lines=True).dropna()

pd.DataFrame({"Scientific Name": df["Scientific Name"].unique(), "Total Count per Species": df.groupby("Scientific Name")["Count"].sum()}).to_csv('/content/drive/MyDrive/Colab Notebooks/Exam/b4_output1.csv')