# -*- coding: utf-8 -*-
"""villadelrey_b8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nG5_atPSdsls9IH0Q1SwlsIh1BsrBQ1
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam/Exam_Table.csv', skip_blank_lines=True).dropna()

df[df['Visibility (m)'] > 8].to_csv('/content/drive/MyDrive/Colab Notebooks/Exam/b8_output1.csv')