# -*- coding: utf-8 -*-
"""villadelrey_b5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1863f26toPuklfB4DwgxLf7punUMK0RKv
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam/Exam_Table.csv', skip_blank_lines=True).dropna()

pd.DataFrame({"Scientific Name": df["Scientific Name"].unique(), "Average Size Est (cm)": df.groupby("Scientific Name")["Size Est (cm)"].mean()}).to_csv('/content/drive/MyDrive/Colab Notebooks/Exam/b5_output1.csv')