# -*- coding: utf-8 -*-
"""villadelrey_b6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14feg3OkbIvJJq-uWL3IRpRHRn-5QR9R3
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam/Exam_Table.csv', skip_blank_lines=True).dropna()

Species = df.Species.unique()
Tcount = df.groupby("Species")["Count"].sum()
Ntable = pd.DataFrame({"Total Count per Species": Tcount})

Ntable.nlargest(1, 'Total Count per Species').to_csv('/content/drive/MyDrive/Colab Notebooks/Exam/b6_output1.csv')