# -*- coding: utf-8 -*-
"""villadelrey_b2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yTA5fHod632UAphvQZPjsx7qItUHXGYL
"""

import pandas as pd

#Rename columns to lowercase and replace spaces with underscores.

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam/Exam_Table.csv', skip_blank_lines=True).dropna()

df.rename(columns = {'Date':'date', 'Location':'location', 'Site':'site', 'Observer':'observer', 'Depth (m)':'depth (m)', 'Visibility (m)':'visibility (m)', 'Replicate':'replicate', 'Interval':'interval', 'Genus':'genus', 'Species':'species', 'Scientific Name':'scientific name', 'Count':'count', 'Size Est (cm)':'size est (cm)'})
df.replace(" ", "_")

#.to_csv('/content/drive/MyDrive/Colab Notebooks/Exam/b2_output1.csv')

from google.colab import drive
drive.mount('/content/drive')