# -*- coding: utf-8 -*-
"""villadelrey_b3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-eUnPBwIQSfBslYgymwPY1OQw2I3t5w0
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Exam/Exam_Table.csv', skip_blank_lines=True).dropna()

df[df['Genus']=='Pomacentrus'].to_csv('/content/drive/MyDrive/Colab Notebooks/Exam/b3_output1.csv')